### ISSUE TITLE
README Command Typo

### ISSUE THREAD

**Issue by PseudoSky** [pruski/generator-fractal#1]
Not sure if this is still ongoing, but on the README in the subcommands sections

`fractal:comp` - module definition
`fractal:ctrl` - directive
`fractal:dir` - controller
`fractal:srv` - service

I'm guessing you accidentally swapped `dir` and `ctrl`
if not, you might consider swapping those?

**Comment by pruski** [comment]
Thanks, updated.

As a tool it is still useful. Unfortunately in the current implementation it is not scalable between projects (unless you clone repo, link it locally and modify the templates) and doesn't support other frameworks. The next iteration will fix that, however it is hard to say when is it going to happen.
